openapi: 3.0.2
info:
  title: E-Kandra API
  description: API for job search platform
  version: 1.0.0
servers:
  - url: http://localhost:8080  # Replace with your server URL
tags:
  - name: offer
    description: Operations related to job offers
  - name: user
    description: Operations related to users
  - name: domain
    description: Operations related to job domains
  - name: category
    description: Operations related to job categories
paths:
  /offers:
    get:
      tags:
        - offer
      summary: Get a list of job offers
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: 1
                  title: Software Engineer
                  company: E-Tech
                  description: Exciting software engineering role
                  location: Anosivavaka Antananarivo
    post:
      tags:
        - offer
      summary: Create a new job offer
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: Data Scientist
              company: Novity
              description: Exciting Data Scientism role
              location: Ivandry Antananarivo
      responses:
        '201':
          description: Offer created successfully
          content:
            application/json:
              example:
                id: 2
                title: Data Scientist
                company: Novity
                description: Exciting Data Scientism role
                location: Ivandry Antananarivo
  /offers/{id}:
    get:
      tags:
        - offer
      summary: Get details of a specific job offer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                title: Software Engineer
                company: E-Tech
                description: Exciting software engineering role
                location: Anosivavaka Antananarivo
    put:
      tags:
        - offer
      summary: Update a specific job offer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: Senior Software Engineer
              company: Pulse
              description: Exciting senior software engineering role
              location: Andranomena Antananrivo
      responses:
        '200':
          description: Offer updated successfully
          content:
            application/json:
              example:
                id: 1
                title: Senior Software Engineer
                company: Pulse
                description: Exciting senior software engineering role
                location: Andranomena Antananarivo
    delete:
      tags:
        - offer
      summary: Delete a specific job offer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '204':
          description: Offer deleted successfully
  /users:
    get:
      tags:
        - user
      summary: Get a list of users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: 1
                  name: Joro Sullivan
                  age: 21
    post:
      tags:
        - user
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Rojosoa Nayah
              age: 18
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              example:
                id: 2
                name: Rojosoa Nayah
                age: 18
  /users/{id}:
    get:
      tags:
        - user
      summary: Get details of a specific user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                name: Joro Sullivan
                age: 21
    put:
      tags:
        - user
      summary: Update a specific user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Rojosoa Nayah
              age: 18
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              example:
                id: 1
                name: Rojosoa Nayah
                age: 18
    delete:
      tags:
        - user
      summary: Delete a specific user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '204':
          description: User deleted successfully
  /domains:
    get:
      tags:
        - domain
      summary: Get a list of job domains
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: 1
                  name: Software Development
    post:
      tags:
        - domain
      summary: Create a new job domain
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Data Analyst
      responses:
        '201':
          description: Domain created successfully
          content:
            application/json:
              example:
                id: 2
                name: Data Analyst
  /domains/{id}:
    get:
      tags:
        - domain
      summary: Get details of a specific job domain
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                name: Software Development
    put:
      tags:
        - domain
      summary: Update a specific job domain
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Web Development
      responses:
        '200':
          description: Domain updated successfully
          content:
            application/json:
              example:
                id: 1
                name: Web Development
    delete:
      tags:
        - domain
      summary: Delete a specific job domain
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '204':
          description: Domain deleted successfully
  /categories:
    get:
      tags:
        - category
      summary: Get a list of job categories
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: 1
                  name: Full-Time
    post:
      tags:
        - category
      summary: Create a new job category
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Part-Time
      responses:
        '201':
          description: Category created successfully
          content:
            application/json:
              example:
                id: 2
                name: Part-Time
  /categories/{id}:
    get:
      tags:
        - category
      summary: Get details of a specific job category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                name: Full-Time
    put:
      tags:
        - category
      summary: Update a specific job category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Freelance
      responses:
        '200':
          description: Category updated successfully
          content:
            application/json:
              example:
                id: 1
                name: Freelance
    delete:
      tags:
        - category
      summary: Delete a specific job category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '204':
          description: Category deleted successfully
