openapi: '3.0.2'
info:
  title: Job finder
  description: Un API pour chercher du travail en ligne
  version: '1'
servers:
  - url: http://localhost:8080
tags:
  - name: job
    description: to manipule job
  - name: user
    description: to manipule user
  - name: type_user
    description: to manipule type_user
  - name: apply_job
    description: to manipule apply_job
  - name: company
    description: to manipule company
  - name: not CRUD
    description: endpoint that not a CRUD
paths:
  /jobs:
    get:
      tags:
        - job
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs'
        '500':
          description: Internal server error
    post:
      tags:
        - job
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/jobs'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs'
        '500':
          description: Internal server error
    patch:
      tags:
        - job
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/jobs'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs'
        '500':
          description: Internal server error
    delete:
      tags:
        - job
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs'
        '500':
          description: Internal server error
  /jobs/:
    get:
      tags:
        - job
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs'
        '500':
          description: Internal server error
  /jobs/name:
    get:
      tags:
        - job
      parameters:
        - name: name
          in: query
          schema:
            type: string
            example: axel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs'
        '500':
          description: Internal server error
  /company:
    get:
      tags:
        - company
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/company'
        '500':
          description: Internal server error
  /company_jobs/count_job:
    get:
      tags:
        - company
        - job
        - not CRUD
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/company'
        '500':
          description: Internal server error
    post:
      tags:
        - company
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/company'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/company'
        '500':
          description: Internal server error
    patch:
      tags:
        - company
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/company'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/company'
        '500':
          description: Internal server error
    delete:
      tags:
        - company
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/company'
        '500':
          description: Internal server error
  /company/:
    get:
      tags:
        - company
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/company'
        '500':
          description: Internal server error
  /company/name:
    get:
      tags:
        - company
      parameters:
        - name: name
          in: query
          schema:
            type: string
            example: axel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/company'
        '500':
          description: Internal server error
  /type_user:
    get:
      tags:
        - type_user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/type_user'
        '500':
          description: Internal server error
    post:
      tags:
        - type_user
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/type_user'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/type_user'
        '500':
          description: Internal server error
    patch:
      tags:
        - type_user
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/type_user'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/type_user'
        '500':
          description: Internal server error
    delete:
      tags:
        - type_user
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/type_user'
        '500':
          description: Internal server error
  /type_user/:
    get:
      tags:
        - type_user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/type_user'
        '500':
          description: Internal server error
  /apply_job:
    get:
      tags:
        - apply_job
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apply_job'
        '500':
          description: Internal server error
    post:
      tags:
        - apply_job
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/apply_job'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apply_job'
        '500':
          description: Internal server error
    patch:
      tags:
        - apply_job
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/apply_job'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apply_job'
        '500':
          description: Internal server error
    delete:
      tags:
        - apply_job
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apply_job'
        '500':
          description: Internal server error
  /apply_job/:
    get:
      tags:
        - apply_job
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apply_job'
        '500':
          description: Internal server error
  /user:
    get:
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '500':
          description: Internal server error
    post:
      tags:
        - user
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '500':
          description: Internal server error
    patch:
      tags:
        - user
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '500':
          description: Internal server error
    delete:
      tags:
        - user
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '500':
          description: Internal server error
  /user/:
    get:
      tags:
        - user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '500':
          description: Internal server error
  /user/name:
    get:
      tags:
        - user
        - not CRUD
      parameters:
        - name: name
          in: query
          schema:
            type: string
            example: axel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '500':
          description: Internal server error
  /company_jobs:
    get:
      tags:
        - job
        - company
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/company_jobs'
        '500':
          description: Internal server error
  /company_jobs/name:
    get:
      tags:
        - job
        - company
        - not CRUD
      parameters:
        - name: name
          in: query
          schema:
            type: string
            example: axel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/company_jobs'
        '500':
          description: Internal server error

components:
  schemas:
    jobs:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: enseigant
        description:
          type: string
          example: jouer le role d un enseignant
    company:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: hei
        description:
          type: string
          example: la haute ecole en informatique
    type_user:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: noob
        description:
          type: string
          example: un debutant
    user:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: axel
        age:
          type: integer
          example: 18
        description:
          type: string
          example: un debutant
        id_type_user:
          type: integer
          example: 1
    apply_job:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        id_user:
          type: integer
          format: int64
          example: 2
        id_job:
          type: integer
          format: int64
          example: 3
    company_jobs:
      type: object
      properties:
        company:
          $ref: '#/components/schemas/company'
        job:
          $ref: '#/components/schemas/jobs'
    company_jobs_count:
      type: object
      properties:
        company:
          $ref: '#/components/schemas/company'
        quantity:
          type: integer
          example: 10
