insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (1, 'Skewes', 'Georgina', 'gskewes0@geocities.com', 'yV1#D"*XF$A8vX.', 263838799, 'RSS');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (2, 'Kennett', 'Marianna', 'mkennett1@quantcast.com', 'xW1@9%{Kh', 2702023174, 'Flight Test');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (3, 'Ragate', 'Erica', 'eragate2@elpais.com', 'uB4({''!Gvy!t', 808452910, 'Hypnotherapy');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (4, 'Portman', 'Agnesse', 'aportman3@wikimedia.org', 'rN4.N_t@cg61', 1176620636, 'TPU');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (5, 'Mallabund', 'Emlyn', 'emallabund4@nytimes.com', 'qG1/_gVa=', 2482782018, 'Succession Planning');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (6, 'O''Deoran', 'Cathrine', 'codeoran5@blogspot.com', 'jM1!|D,eJ2Nd??)', 9494740154, 'Quantitative Analytics');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (7, 'Cowherd', 'Gabriello', 'gcowherd6@aboutads.info', 'wT3~DJA0I\', 8936235941, 'CPLEX');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (8, 'Cohan', 'Filip', 'fcohan7@alibaba.com', 'bT8+p"F1W*!_c`$$', 9571095892, '3D Visualization');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (9, 'Jerman', 'Kaleb', 'kjerman8@ibm.com', 'xT5&#7F@2"ROUy*c', 5277152832, 'GNU C++');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (10, 'Donett', 'Georg', 'gdonett9@live.com', 'eE7,@Pc~/@8!c', 8767179919, 'MQC');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (11, 'Orviss', 'Aldis', 'aorvissa@chron.com', 'jD1)C>T}s', 3500131569, 'OSHA 30-Hour');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (12, 'Diemer', 'Rollin', 'rdiemerb@dot.gov', 'aX2+,p.ULE/%', 4532871521, 'Festivals');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (13, 'Cashford', 'Dianne', 'dcashfordc@opensource.org', 'tO3.IIrR|z{@Rq', 2272300236, 'DNA electrophoresis');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (14, 'Jandera', 'Janeen', 'jjanderad@wikimedia.org', 'kU0//JS~~}gT#tN', 1657433561, 'HBDI');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (15, 'Abbatucci', 'Maudie', 'mabbatuccie@sbwire.com', 'oP4&d/?on''(0o', 459572722, 'Stage Make-up');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (16, 'Ausello', 'Danit', 'dausellof@msu.edu', 'fV8*)X{MUu~lL68', 5436940106, 'Executive Protection');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (17, 'Klessmann', 'Hilda', 'hklessmanng@youtu.be', 'rH2"1#wcGzpWL=p', 3692668993, 'DDR2');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (18, 'MacLise', 'Dorine', 'dmacliseh@umn.edu', 'fO4$oyMVbQm', 7234654068, 'Omnet++');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (19, 'Filipczak', 'Zorah', 'zfilipczaki@shop-pro.jp', 'mI4#rt,k&QA', 6947649546, 'CA Unicenter NSM');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (20, 'Lythgoe', 'Ravid', 'rlythgoej@pagesperso-orange.fr', 'kU8,szA_Sfa', 4263288174, 'BIM');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (21, 'Mager', 'Esther', 'emagerk@dailymail.co.uk', 'aL8*RrP@I1}\5', 7523169694, 'CentOS');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (22, 'Fahy', 'Tarrance', 'tfahyl@imgur.com', 'cS6?v&&DC)e_Be)', 5183133727, 'Professional Ethics');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (23, 'Burnip', 'Mariam', 'mburnipm@shareasale.com', 'cL6"gO~8%qK3)F', 1901432174, 'Mobile Marketing');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (24, 'Fayerman', 'Lauri', 'lfayermann@devhub.com', 'xP6>!cDU!s6)|', 1735606042, 'RWA');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (25, 'Welbeck', 'Wilone', 'wwelbecko@free.fr', 'gR8#e*(=_pWC<Bj', 9738200662, 'Content Writing');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (26, 'Gregor', 'Neddie', 'ngregorp@indiatimes.com', 'nK3(=hRUg,yo`', 4305173696, 'Process Optimization');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (27, 'Winchcomb', 'Chrisse', 'cwinchcombq@cnbc.com', 'lC9\{gHq', 1613929731, 'VMware Certified Professional');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (28, 'Goult', 'Howard', 'hgoultr@cbslocal.com', 'eB6|zU@/n', 5816176267, 'global HCM');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (29, 'Boules', 'Rolfe', 'rbouless@hibu.com', 'rZ0<gKMVta', 9600539945, 'Overhaul');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (30, 'Gillow', 'Heda', 'hgillowt@wordpress.com', 'lT0(Z5P9', 1965728000, 'MPEG2');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (31, 'Obray', 'Sarene', 'sobrayu@diigo.com', 'hZ9?H|<"5\z/', 3346254155, 'PMO Development');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (32, 'Verbeke', 'Freeland', 'fverbekev@drupal.org', 'oR9?Gc!~l', 7862589356, 'CPR Instruction');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (33, 'Lobe', 'Hans', 'hlobew@discuz.net', 'kD3.7QrC', 4827701075, 'Oil Analysis');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (34, 'McCoid', 'Shaine', 'smccoidx@comcast.net', 'yQ3/hY1WOsfMJ', 9605420230, 'HP EVA');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (35, 'Mungane', 'Cristian', 'cmunganey@elegantthemes.com', 'zE3_(2@|Ed~{_dGa', 7552769227, 'Online Travel');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (36, 'Lockhurst', 'Colene', 'clockhurstz@github.io', 'wC3@=$Udem', 8623430618, 'Non-profit Volunteering');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (37, 'Elvidge', 'Gates', 'gelvidge10@mapy.cz', 'jH1,6Vqt1CG', 8031096476, 'Verilog');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (38, 'Krause', 'Caspar', 'ckrause11@princeton.edu', 'dK8&n})c~G!h,Z', 8012542598, 'Functional Specifications');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (39, 'Halden', 'Vitia', 'vhalden12@wix.com', 'dM9*}tsx6', 3501090201, 'Krav Maga');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (40, 'Harry', 'Nora', 'nharry13@symantec.com', 'gD3<Nkk3wGh', 608222214, 'XSL');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (41, 'Daltry', 'Marlo', 'mdaltry14@unicef.org', 'oO5?cl)QzG&\4ObW', 7405616635, 'ETL Tools');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (42, 'McGraith', 'Gilly', 'gmcgraith15@timesonline.co.uk', 'sM8*nAFMnxUOSSzv', 491030237, 'Work Very Well with Others');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (43, 'Adamowitz', 'Mortie', 'madamowitz16@arizona.edu', 'rU6/XGRISuFxw', 3086648849, 'Zemax');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (44, 'Tuddenham', 'Claudio', 'ctuddenham17@cam.ac.uk', 'bN7~%\JV', 7038601022, 'Utility Industry');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (45, 'Beddoes', 'Daron', 'dbeddoes18@psu.edu', 'wG7#iAyCpEuTr', 7060434986, 'Microsoft Dynamics NAV');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (46, 'Brunroth', 'Son', 'sbrunroth19@spotify.com', 'aC0\"!S25y?2S', 2577126720, 'DxDesigner');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (47, 'Leydon', 'Gearalt', 'gleydon1a@free.fr', 'gT5$B)>We?@IgdRw', 6798614604, 'Waterfall');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (48, 'Taffee', 'Tynan', 'ttaffee1b@comcast.net', 'wK8#$l6Ku5x0W|a', 7324197571, 'Zmap');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (49, 'Kobisch', 'Kevina', 'kkobisch1c@aboutads.info', 'uR1<a9Ov<~m', 9577227125, 'Kaizen Leadership');
insert into "user" (id, user_name, user_firstname, email, password, mobile, skills) values (50, 'Managh', 'Nannie', 'nmanagh1d@odnoklassniki.ru', 'fT7>jwGzlom', 8085457288, 'Bass Guitar');
